version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    ports:
      - "8880:8080"
    environment:
      KC_HOSTNAME: localhost
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://pg:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HEALTH_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./dev_setup/keycloak/regtech-test-realm.json:/opt/keycloak/data/import/regtech-test-realm.json:ro
      - ./dev_setup/keycloak/healthcheck.sh:/mnt/healthcheck.sh
    command: start-dev --import-realm
    healthcheck:
      test: ["CMD-SHELL", "bash /mnt/healthcheck.sh"]
      interval: 5s
      timeout: 2s
      retries: 15
    depends_on:
      pg:
        condition: service_healthy
    profiles: [locust, backend]
  pg:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
      - ./dev_setup/db/:/docker-entrypoint-initdb.d/:ro
    profiles: [locust, backend]
  user-fi:
    build: ../regtech-user-fi-management
    ports:
      - 8881:8888
    env_file:
      - ./dev_setup/common.env
      - ./dev_setup/user-fi.local.env
    #healthcheck:
    #  test: ["CMD-SHELL", "wget --output-document - http://localhost:8888/docs"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5
    depends_on:
      keycloak:
        condition: service_healthy
      pg:
        condition: service_healthy
    profiles: [backend]
  filing:
    build: ../sbl-filing-api
    ports:
      - 8882:8888
    env_file:
      - ./dev_setup/common.env
      - ./dev_setup/filing.local.env
    healthcheck:
      test: ["CMD-SHELL", "wget --output-document - http://localhost:8888/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      keycloak:
        condition: service_healthy
      pg:
        condition: service_healthy
    profiles: [locust, backend]

  mail-api:
    build: ../regtech-mail-api
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
      - 8765:8765
    env_file:
      - ./dev_setup/common.env
    environment:
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      FROM_ADDR: noreply@localhost.localdomain
      TO: cases@localhost.localdomain
    profiles: [backend]

  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    profiles: [backend]

  sbl-locust:
    build: ../sbl-filing-api/locust-load-test
    ports:
      - 8089:8089
    env_file:
      - ./dev_setup/common.env
    environment:
      MODE: single
      USER_INDEX: 100
      SBLAR_REPO: https://api.github.com/repos/cfpb/sbl-test-data/contents/locust-sblars
    profiles: [locust]

  sbl-frontend:
    build: ../sbl-frontend
    ports:
      - 8898:8080
    env_file:
      - ./dev_setup/frontend.local.env
    profiles: [frontend]

  cleanup:
    build: ../regtech-cleanup-api
    ports:
      - 8883:8888
    env_file:
      - ./dev_setup/common.env
      - ./dev_setup/filing.local.env
      - ./dev_setup/user-fi.local.env
    depends_on:
      filing:
        condition: service_healthy
      user-fi:
        condition: service_healthy
    profiles: [backend]
volumes:
  db:
    driver: local