version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - "8880:8080"
    environment:
      KC_HOSTNAME: keycloak
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://pg:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HEALTH_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./dev_setup/keycloak/regtech-test-realm.json:/opt/keycloak/data/import/regtech-test-realm.json:ro
      - ./dev_setup/keycloak/healthcheck.sh:/mnt/healthcheck.sh
    command: start-dev --import-realm
    healthcheck:
      test: ["CMD-SHELL", "bash /mnt/healthcheck.sh"]
      interval: 5s
      timeout: 2s
      retries: 15
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
      - ./dev_setup/db/:/docker-entrypoint-initdb.d/:ro
  user_fi:
    build: ../regtech-user-fi-management
    ports:
      - 8881:8888
    environment:
      ENV: DOCKER
      KC_URL: http://keycloak:8080
      KC_REALM: regtech
      KC_ADMIN_CLIENT_ID: admin-cli
      KC_ADMIN_CLIENT_SECRET: "**********"
      AUTH_CLIENT: regtech-client
      INST_DB_NAME: financial_institutions
      INST_DB_USER: fi
      INST_DB_PWD: fi
      INST_DB_HOST: pg:5432
      INST_DB_SCHEMA: public
    healthcheck:
      test: ["CMD-SHELL", "wget --output-document - http://localhost:8888/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      keycloak:
        condition: service_healthy
      pg:
        condition: service_healthy
volumes:
  db:
    driver: local