INSERT INTO hmda_institution_type (id,"name") VALUES
	 ('1','National Bank (OCC supervised)'),
	 ('2','State Member Bank (FRS Supervised):'),
	 ('3','State non-member bank (FDIC supervised)'),
	 ('4','State Chartered Thrift (FDIC supervised)'),
	 ('5','Federal Chartered Thrift (OCC supervised)'),
	 ('6','Credit Union (NCUA supervised)'),
	 ('7','Federal Branch or Agency of Foreign Banking Organization (FBO)'),
	 ('8','Branch or Agency of FBO (FRS supervised)'),
	 ('9','MBS of national Bank (OCC supervised)'),
	 ('10','MBS of state member bank (FRS supervised)'),
	 ('11','MBS of state non-member bank (FDIC supervised)'),
	 ('12','MBS of Bank Holding Company (BHC) (FRS supervised)'),
	 ('13','MBS of credit union (NCUA supervised)'),
	 ('14','independent MBS, no depository affiliation'),
	 ('15','MBS of Savings and Loan Holding Co'),
	 ('16','MBS of state chartered Thrift'),
	 ('17','MBS of federally chartered thrift (OCC supervised)'),
	 ('18','Affiliate of depository institution. MBS is in the same ownership org as a depository.');
